### ISSUE TITLE
#include path errors

### ISSUE THREAD

**Issue by nscheuer** [nic2703/Innoprojekt_22#5]
somehow, vscode fails to allow us to have more than one .vscode folder in order to run the windows gcc compiler for cpp and the arduino c compiler. We have tried moving the .vscode folder in the respective subfolder (for arduino or c++) but this just results in more errors (according to thesmilingturtle). 

Currently the repository is set up for arduino compiling.

**Comment by dragonracer9** [comment]
well idk i fixed my stuff and its really quite liberating having intellisense back to tell you what you did wrong.
dunno how i can help u but dm me on the discord if you still have that issue
