### ISSUE TITLE
The cpp bluetooth connection attempt unnecessary

### ISSUE THREAD

**Issue by TheSmilingTurtle** [nic2703/Innoprojekt_22#6]
The [Cpp Bluetooth](https://github.com/nic2703/Innoprojekt_22/blob/b26cc99316e5d88f55918f41b9d2860407b6f5c1/Windows/cpp/BT_Connect_attempt.cpp) file seems unnecessary now that logging can be done by [data_logger.py](https://github.com/nic2703/Innoprojekt_22/blob/b26cc99316e5d88f55918f41b9d2860407b6f5c1/Windows/Python/Logging/data_logger.py) and connecting for other purposes is now possible from any android phone.

**Comment by dragonracer9** [comment]
heyy, I've branched and re-organized some of the unnecessary files in the motor driver category. What files exactly are now obsolete? If you can chuck the obsolete files into UNUSED, that would be great. We can discuss the files we wanna keep later.

**Comment by dragonracer9** [comment]
well it would seem data logging in py is really quite good
gonna clean the folder, what do ya say

**Comment by dragonracer9** [comment]
done
