### ISSUE TITLE
the mandala function lacks maths

### ISSUE THREAD

**Issue by dragonracer9** [nic2703/Innoprojekt_22#8]
would it be ok if someone could explain the maths for the mandala thing to me bc it rlly needs to be done

**Comment by nscheuer** [comment]
take a quadratic or higher function f(x) = ax³+..., which will have 4 or more unknowns. set up a LGS with the conditions being that the start and end points at x = 0 and x = like 5 maybe have to correspond to the start and end points of the next quadratic. Another condition is that the function should not exceed the bounds (aka go under y=0 and above y=10 (for example)). 

You will receive an answer from matlab in the form of a linearkombination of a 4 or more dimensional vector. use rand() for the scalars and voila, many different quadratic (or higher) curves to draw. Then, use a rotational transformation to turn this x-y plot into a rho-phi plot in polar coordinates. You can have it be in slices of 4 or 8 or 5 idk as long as they can be stitched together. 

The rho-phi plot can be turned back into piecewise parametric curves taking t. Iterate through t to find as many points as needed and interpolate between them using lines.

**Comment by dragonracer9** [comment]
﻿
﻿
Hi nic,

Thx for the reply. Gotta ask about the rotational transformation. How does that work exactly?
Cheers



Sent from my iPhone
On 23 Apr 2022, at 17:28, Nic ***@***.***> wrote:

﻿

take a quadratic or higher function f(x) = ax³+..., which will have 4 or more unknowns. set up a LGS with the conditions being that the start and end points at x = 0 and x = like 5 maybe have to correspond to the start and end points of the next quadratic. Another condition is that the function should not exceed the bounds (aka go under y=0 and above y=10 (for example)).

You will receive an answer from matlab in the form of a linearkombination of a 4 or more dimensional vector. use rand() for the scalars and voila, many different quadratic (or higher) curves to draw. Then, use a rotational transformation to turn this x-y plot into a rho-phi plot in polar coordinates. You can have it be in slices of 4 or 8 or 5 idk as long as they can be stitched together.

The rho-phi plot can be turned back into piecewise parametric curves taking t. Iterate through t to find as many points as needed and interpolate between them using lines.

**Comment by nscheuer** [comment]
this could be an interpretation:
https://www.desmos.com/calculator/dhfgkrj0xh

**Comment by dragonracer9** [comment]
would seem this unnecessary rn
